-- SurveyFlow + Supabase complete database/storage setup
-- IMPORTANT: This version intentionally allows anonymous CRUD because the current
-- SurveyFlow app has no login/auth flow. Add Supabase Auth/RLS restrictions before
-- using this with sensitive production data.

create extension if not exists pgcrypto;

create table if not exists public.survey_records (
  id text primary key,
  survey_number text not null unique,
  policy_number text,
  registration_number text,
  document_type text,
  status text,
  confidence numeric,
  record jsonb not null,
  raw_text text default '',
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create index if not exists idx_survey_records_policy_number on public.survey_records(policy_number);
create index if not exists idx_survey_records_registration_number on public.survey_records(registration_number);
create index if not exists idx_survey_records_updated_at on public.survey_records(updated_at desc);
create index if not exists idx_survey_records_record_gin on public.survey_records using gin(record);

create table if not exists public.survey_parts (
  id bigint generated by default as identity primary key,
  survey_id text not null references public.survey_records(id) on delete cascade,
  row_id text not null,
  e_no text,
  parts_description text,
  hsn_code text,
  bill_s_no text,
  remark text,
  estimated numeric default 0,
  glass_second_hand_repair numeric,
  metal_35 numeric,
  non_metal numeric,
  gst_rate numeric default 0,
  selected_for_final boolean default true,
  unique(survey_id, row_id)
);
create index if not exists idx_survey_parts_survey on public.survey_parts(survey_id);

create table if not exists public.survey_labour (
  id bigint generated by default as identity primary key,
  survey_id text not null references public.survey_records(id) on delete cascade,
  row_id text not null,
  s_no text,
  sac text,
  bill_s_no text,
  labour_description text,
  estimated numeric default 0,
  assessed numeric default 0,
  gst_rate numeric default 0,
  total numeric default 0,
  selected_for_final boolean default true,
  unique(survey_id, row_id)
);
create index if not exists idx_survey_labour_survey on public.survey_labour(survey_id);

create table if not exists public.survey_invoices (
  id bigint generated by default as identity primary key,
  survey_id text not null references public.survey_records(id) on delete cascade,
  row_id text not null,
  invoice_number text,
  invoice_date date,
  invoice_amount numeric default 0,
  vendor text,
  gst_number text,
  description text,
  unique(survey_id, row_id)
);
create index if not exists idx_survey_invoices_survey on public.survey_invoices(survey_id);

create table if not exists public.survey_client_documents (
  id bigint generated by default as identity primary key,
  survey_id text not null references public.survey_records(id) on delete cascade,
  document_id text not null,
  document_name text,
  status text,
  remarks text,
  unique(survey_id, document_id)
);

create table if not exists public.survey_company_documents (
  id bigint generated by default as identity primary key,
  survey_id text not null references public.survey_records(id) on delete cascade,
  document_id text not null,
  document_name text,
  status text,
  remarks text,
  unique(survey_id, document_id)
);

create table if not exists public.survey_photos (
  id bigint generated by default as identity primary key,
  survey_id text not null references public.survey_records(id) on delete cascade,
  photo_id text not null,
  file_name text,
  caption text,
  captured_at text,
  public_url text,
  unique(survey_id, photo_id)
);
create index if not exists idx_survey_photos_survey on public.survey_photos(survey_id);

create table if not exists public.survey_files (
  id text primary key,
  survey_id text not null references public.survey_records(id) on delete cascade,
  file_name text not null,
  file_type text,
  file_size bigint default 0,
  storage_path text not null,
  public_url text,
  uploaded_at timestamptz not null default now()
);
create index if not exists idx_survey_files_survey on public.survey_files(survey_id);

-- DB-backed sequential reference numbers: SF/SRV/YYYY/MM/0001 ...
create table if not exists public.survey_sequences (
  year_no integer not null,
  month_no integer not null,
  last_number integer not null default 0,
  primary key(year_no, month_no)
);

create or replace function public.generate_survey_number()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_year integer := extract(year from now())::integer;
  v_month integer := extract(month from now())::integer;
  v_next integer;
begin
  insert into public.survey_sequences(year_no, month_no, last_number)
  values (v_year, v_month, 1)
  on conflict (year_no, month_no)
  do update set last_number = public.survey_sequences.last_number + 1
  returning last_number into v_next;

  return format('SF/SRV/%s/%s/%s', v_year, lpad(v_month::text, 2, '0'), lpad(v_next::text, 4, '0'));
end;
$$;

grant execute on function public.generate_survey_number() to anon, authenticated;

-- RLS: current app has no login, so anonymous users can read/write survey data.
alter table public.survey_records enable row level security;
alter table public.survey_parts enable row level security;
alter table public.survey_labour enable row level security;
alter table public.survey_invoices enable row level security;
alter table public.survey_client_documents enable row level security;
alter table public.survey_company_documents enable row level security;
alter table public.survey_photos enable row level security;
alter table public.survey_files enable row level security;
alter table public.survey_sequences enable row level security;

drop policy if exists survey_records_anon_all on public.survey_records;
create policy survey_records_anon_all on public.survey_records for all to anon, authenticated using (true) with check (true);

drop policy if exists survey_parts_anon_all on public.survey_parts;
create policy survey_parts_anon_all on public.survey_parts for all to anon, authenticated using (true) with check (true);

drop policy if exists survey_labour_anon_all on public.survey_labour;
create policy survey_labour_anon_all on public.survey_labour for all to anon, authenticated using (true) with check (true);

drop policy if exists survey_invoices_anon_all on public.survey_invoices;
create policy survey_invoices_anon_all on public.survey_invoices for all to anon, authenticated using (true) with check (true);

drop policy if exists survey_client_documents_anon_all on public.survey_client_documents;
create policy survey_client_documents_anon_all on public.survey_client_documents for all to anon, authenticated using (true) with check (true);

drop policy if exists survey_company_documents_anon_all on public.survey_company_documents;
create policy survey_company_documents_anon_all on public.survey_company_documents for all to anon, authenticated using (true) with check (true);

drop policy if exists survey_photos_anon_all on public.survey_photos;
create policy survey_photos_anon_all on public.survey_photos for all to anon, authenticated using (true) with check (true);

drop policy if exists survey_files_anon_all on public.survey_files;
create policy survey_files_anon_all on public.survey_files for all to anon, authenticated using (true) with check (true);

drop policy if exists survey_sequences_anon_select on public.survey_sequences;
create policy survey_sequences_anon_select on public.survey_sequences for select to anon, authenticated using (true);

-- Supabase Storage bucket for PDFs/images/source documents.
insert into storage.buckets (id, name, public)
values ('survey-files', 'survey-files', true)
on conflict (id) do update set public = true;

drop policy if exists survey_files_storage_read on storage.objects;
create policy survey_files_storage_read on storage.objects for select to anon, authenticated
using (bucket_id = 'survey-files');

drop policy if exists survey_files_storage_insert on storage.objects;
create policy survey_files_storage_insert on storage.objects for insert to anon, authenticated
with check (bucket_id = 'survey-files');

drop policy if exists survey_files_storage_update on storage.objects;
create policy survey_files_storage_update on storage.objects for update to anon, authenticated
using (bucket_id = 'survey-files') with check (bucket_id = 'survey-files');

drop policy if exists survey_files_storage_delete on storage.objects;
create policy survey_files_storage_delete on storage.objects for delete to anon, authenticated
using (bucket_id = 'survey-files');

-- Optional verification queries:
-- select count(*) from public.survey_records;
-- select * from public.survey_parts order by id desc limit 20;
-- select * from public.survey_labour order by id desc limit 20;
-- select * from public.survey_files order by uploaded_at desc limit 20;
-- select * from public.survey_photos order by id desc limit 20;
